"""Fixed User.blacklisted_tokens uselist

Revision ID: 5a8b9144482d
Revises: a6f2e5a89562
Create Date: 2024-05-09 12:32:52.335510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8b9144482d'
down_revision: Union[str, None] = 'a6f2e5a89562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
