"""Models change

Revision ID: 987f7a73f168
Revises: c40fa6ab95b4
Create Date: 2024-05-12 20:17:23.274069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987f7a73f168'
down_revision: Union[str, None] = 'c40fa6ab95b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('history', 'picture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('history', 'rate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'rate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history', 'picture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
